# Commands to start on workspace startup
image:
  file: .gitpod.Dockerfile
tasks:
  - init: yarn add
    command: yarn run start
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview